### ISSUE TITLE
Enhancement: Change debug to an option in the config file

### ISSUE THREAD

**Issue by bdf0506** [andrewfraley/arris_cable_modem_stats#12]
Rather than have Debug be a setting when you run the program, this should be moved (or added) to the configuration file. When running this in a docker container, it's rather difficult to temporarily enable debug. I've had to actually have a separate docker container that has the Dockerfile modified for the run command to be --debug. If it was in the config file, you could simply share the config file with your docker container, modify the variable in config.ini, restart the docker container and then you have debug running.

**Comment by andrewfraley** [comment]
support for this has been added on the refresh_token branch

**Comment by andrewfraley** [comment]
This is now supported via setting ```arris_debug_stats = True``` in the config file or ENV variable
