### ISSUE TITLE
Grafana Dashboard not displaying data

### ISSUE THREAD

**Issue by DevinCampbell** [andrewfraley/arris_cable_modem_stats#3]
I have the script running and if I use InfluxQL I can see that data is being successfully written to the InfluxDB database, but I'm not getting any results from your provided sb8200_grafana.json. It successfully imports the dashboard via file but no data displays. I tried restarting InfluxDB and Grafana but it didn't make a difference. Honestly, your queries are beyond what I normally use for my own dashboards so I am not sure what is wrong.

**Comment by DevinCampbell** [comment]
```
docker logs modem_monitoring
2019-08-31 03:14:46,416 INFO     Retreiving stats from http://192.168.100.1/cmconnectionstatus.html
2019-08-31 03:14:50,839 INFO     Parsing HTML for modem model sb8200
2019-08-31 03:14:50,930 INFO     Sending stats to InfluxDB (192.168.1.10:8086)
2019-08-31 03:14:50,959 INFO     Successfully wrote data to InfluxDB
2019-08-31 03:14:50,959 INFO     Sleeping for 300 seconds
```

Logs don't show anything useful.

**Comment by andrewfraley** [comment]
Do you see the measurements when running (in influx)

    show measurements on cable_modem_stats

**Comment by DevinCampbell** [comment]
Yes

**Comment by DevinCampbell** [comment]
The only difference is that I named my InfluxDB database modem_monitoring.

**Comment by andrewfraley** [comment]
In grafana you need to add a new database connection to modem_monitoring.  Then when you import the dashboard it should ask you for the database name to use.  Did you do all of that?  Also make sure you're on the latest Grafana version as I updated my instance to the latest version before exporting.

**Comment by andrewfraley** [comment]
Also try manually running the queries that Grafana is using and see if you get results.

**Comment by DevinCampbell** [comment]
Ahh I had my Datasource in Grafana misconfigured from when I previously tried to get this working with a separate project. It's working now.
