### ISSUE TITLE
Support for Splunk

### ISSUE THREAD

**Issue by michaelcolson** [andrewfraley/arris_cable_modem_stats#38]
Would it be possible to write to a flat file or send to Splunk HTTP Event Collector (HEC) directly?  It looks like the way you've architected the app that a new arris_stats_splunk.py destination could be created.

**Comment by andrewfraley** [comment]
Hi @michaelcolson, yes you would just add a new output function and then call it [at the end of main() here](https://github.com/andrewfraley/arris_cable_modem_stats/blob/3698993c6bb60920b388f91446e662c0f0627b78/src/arris_stats.py#L97).

**Comment by andrewfraley** [comment]
Hi @michaelcolson, I went ahead and added support.  Please see the Splunk section of the readme.  I made no attempt to organize the data specifically for Splunk and I'm just sending it as json data to the HTTP Endpoint Collector.  Let me know if you think the data needs a different structure, but I can see everything there in my test instance, I just don't have any experience creating Splunk dashboards.
