### ISSUE TITLE
Comcast/XFinity turned off http and uses https with basic auth and cookies as of October 28 2020 00:30 PDT in my region(Seattle area)

### ISSUE THREAD

**Issue by jgarland79** [andrewfraley/arris_cable_modem_stats#9]
@andrewfraley The login is admin and the password is the last 8 digits of the modem's serial number. I was able to make some really ugly changes to the script to make it work, but it doesn't seem to work reliably. It works for a few minutes and then goes back to not accepting the credential cookie required to auth to it. I'll submit a PR once I'm more confident with my changes, but I thought I would give you a heads up.

**Comment by jgarland79** [comment]
https://arris.secure.force.com/consumers/articles/General_FAQs/SB8200-Web-Manager-Access

**Comment by jgarland79** [comment]
https://www.dslreports.com/forum/r32907877-Firmware-SB8200-New-Firmware-Password-Required

**Comment by andrewfraley** [comment]
@jgarland79 thanks for the info.  I also have Comcast and my modem was recently updated.  I was able to get authentication to work, but the modem seems to reject all authentication after a period of time or number of requests, as in I can't authenticate using my real browser even.  I'll investigate further as time allows.

**Comment by andrewfraley** [comment]
@jgarland79 I think I have this working reliably.  You can try the "auth" branch if you want to test it.  Note the updated [config.ini](https://github.com/andrewfraley/arris_cable_modem_stats/blob/auth/script/config.ini) file.

**Comment by andrewfraley** [comment]
merged into master, please reopen this if there's any trouble
